name: Deploy FastAPI with Docker

on:
  push:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create .env file from GitHub secret
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Docker image
        run: docker build -t myfastapi-app .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --env-file .env myfastapi-app
